version: "3"
  
services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    command: sh /backend/entrypoint.sh
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    image: node:8.9
    working_dir: /frontend
    command: sh entrypoint.sh
    volumes:
      - ./frontend/:/frontend
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports: 
      - '80:8080'
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
volumes:
  postgres_data:
